## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file sagetex-2.sagetex.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_28 = Integer(28); _sage_const_10 = Integer(10); _sage_const_22 = Integer(22); _sage_const_23 = Integer(23); _sage_const_26 = Integer(26)## This file (sagetex-2.sagetex.sage) was *autogenerated* from sagetex-2.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('sagetex-2', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
try:
 _st_.inline(_sage_const_0 , latex(_sage_const_26 **_sage_const_3 *_sage_const_10 **_sage_const_3 ))
except:
 _st_.goboom(_sage_const_22 )
try:
 _st_.plot(_sage_const_0 , format='notprovided', _p_=plot(sin(x), _sage_const_0 , pi))
except:
 _st_.goboom(_sage_const_23 )
try:
 _st_.commandline(_sage_const_0 , r"""
sage: 1+1
2
sage: factor(x^2 + 2*x + 1)
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_28 )
_st_.endofdoc()
