## -*- encoding: utf-8 -*-
## This file (sagetex-2.sagetex.sage) was *autogenerated* from sagetex-2.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('sagetex-2', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
try:
 _st_.commandline(0, r"""
sage: a1=2
sage: a2=3
sage: sum=a+b
sage: sum
""", globals(), locals(), True)
except:
 _st_.goboom(28)
_st_.endofdoc()
