r"""
This file was *autogenerated* from sagetex-2.tex with sagetex.sty
version 2012/01/16 v2.3.3-69dcb0eb93de. It contains the contents of all the
sageexample environments from sagetex-2.tex. You should be able to
doctest this file with "sage -t sagetex-2_doctest.sage".

It is always safe to delete this file; it is not used in typesetting your
document.

Sage commandline, line 24::

sage: 1+1
2
sage: factor(x^2 + 2*x + 1)

"""
