## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file sagemath中变量的基本应用.sagetex.sage
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_44 = Integer(44); _sage_const_39 = Integer(39); _sage_const_34 = Integer(34); _sage_const_51 = Integer(51)## This file (sagemath中变量的基本应用.sagetex.sage) was *autogenerated* from sagemath中变量的基本应用.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('sagemath中变量的基本应用', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
try:
 _st_.commandline(_sage_const_0 , r"""
sage: a1=2
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_34 )
try:
 _st_.commandline(_sage_const_1 , r"""
sage: a2=3
sage: sum=a1+a2
sage: sum
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_39 )
try:
 _st_.doctest(_sage_const_0 , r"""
sage: a1=2;a2=3;sum1=a1+a2;sum2=a1-a2
sage: sum1;sum2
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_44 )
try:
 _st_.doctest(_sage_const_1 , r"""
sage: a1=2
sage: a2=2^2+3*4+(a1>5)
sage: a2
""", globals(), locals(), False)
except:
 _st_.goboom(_sage_const_51 )
_st_.endofdoc()
